# Generated by Django 2.2.17 on 2020-11-29 19:39

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geom_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('area', models.IntegerField()),
                ('rooms', models.IntegerField(null=True)),
                ('garage', models.BooleanField(null=True)),
                ('other', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'db_table': 'assets_asset',
            },
        ),
    ]
